### ISSUE TITLE
Pytorch not installing on macos

### ISSUE THREAD

**Issue by v0nreagan** [joeyballentine/chaiNNer#747]
Clicking "Pytorch not installed" opens up dependency manager, clicking button next to "Pytorch Not installed" in dependency manager outputs Looking in links download.pytorch.org/blahblah in console but nothing happens for hours. You can restart as many times as you want, modules are not being downloaded.

**Comment by joeyballentine** [comment]
Thanks for letting me know. Mac isn't well tested unfortunately, but I'll see if I can figure out why that's not working.

**Comment by jeremyDayslice** [comment]
Also running into this on MacOS.

![Screen Shot 2022-08-17 at 11 28 12 PM](https://user-images.githubusercontent.com/89921859/185286672-d834fd00-d8a8-471f-9a33-7a82f3c0fa2f.png)

**Comment by joeyballentine** [comment]
What version of macos are you on?

**Comment by v0nreagan** [comment]
MacOS 12.3

**Comment by justinasv775** [comment]
Same thing here, no installing, MacOS 12.5

**Comment by RunDevelopment** [comment]
From the screenshot by @jeremyDayslice, there seems to be something seriously wrong with your python installation. We only show "Python (unknown)" if chainner can't find the integrated python installation, so that is likely why it can't install anything.

@v0nreagan, @justinasv775 Do you also have "Python (unknown)"?

Also, could you all please send us your logs? In chainner's menu, click _Help_ > _Open logs folder_, create a zip with `main.log` and `renderer.log`, and [attach the zip file to a comment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files).

**Privacy information**: These log files contain file paths of chainner's files. The file paths may contain the name of your account (e.g. `Users/michael/...`). If your account is your real name, and you are not comfortable sharing, then do not upload your logs.

**Comment by jeremyDayslice** [comment]
@RunDevelopment the screenshot is from when it was using the bundled Python.  Once I went into the settings and said use my local Python it stopped opening entirely, getting stuck at Loading Dependencies on the splash screen.

**Comment by v0nreagan** [comment]
Now on 0.11.1 - yes integrated python is still listed as "Python (unknown)", I can also confirm that switching to an external python stops chainner from opening and requires scrapping all profile in Application Support folder. 
In 0.11.1 download behaviour is the same - console outputs link to download.python.org and never progresses any further, download of NCNN provides no output in console at all (and never progresses) while download of ONNX produces collecting.. goes all the way to "preparing metadata finished" but ends with status "error". 
 
Logs attached:
[logs_chainner.zip](https://github.com/joeyballentine/chaiNNer/files/9374997/logs_chainner.zip)

**Comment by joeyballentine** [comment]
I will do some debugging on a MacBook when I can and try to figure out what's going wrong here. Not sure when I will be able to though

**Comment by RunDevelopment** [comment]
> I can also confirm that switching to an external python stops chainner from opening and requires scrapping all profile in Application Support folder.

Yeah, that is a huge problem. You should be able to change settings without python working. However, fixing this will require us to rethink the way we structure chainner's application lifecycle, so this won't happen anytime soon.

**Comment by jaroslav-pors** [comment]
I just tested local build with [#763](https://github.com/joeyballentine/chaiNNer/pull/763), [#764](https://github.com/joeyballentine/chaiNNer/pull/764), [#765](https://github.com/joeyballentine/chaiNNer/pull/765), [#766](https://github.com/joeyballentine/chaiNNer/pull/766), [#767](https://github.com/joeyballentine/chaiNNer/pull/767) and it seems to be working. No more Python (unknown)

- macOS 12.3.1, Apple M1
- node 16

<img width="745" alt="Screenshot 2022-08-19 at 9 41 03" src="https://user-images.githubusercontent.com/34416847/185571502-673d1f3e-14b5-4e8a-ae51-e86d5c60a15a.png">

**Comment by joeyballentine** [comment]
Awesome! Thanks for testing that

**Comment by andyderuyter** [comment]
Having the same issues on a Macbook Pro M1 (OSX version 12.3)

<img width="744" alt="Screenshot at Aug 19 10-52-50" src="https://user-images.githubusercontent.com/646590/185583002-1f8505f2-a709-4fe2-bab4-f98e624c89ef.png">

When selecting "Use system Python" in the settings it fails to start the app (throws an error). Had to delete the use system python file from Application Support folder.

**Comment by joeyballentine** [comment]
@andyderuyter I believe this is fixed by #764. I should have that released later today

**Comment by v0nreagan** [comment]
Well done Joey, 0.11.2 - Python version displayed, pytorch installs fine (NCNN and ONNX still doesn't).

**Comment by joeyballentine** [comment]
@v0nreagan do you have an M1?

**Comment by v0nreagan** [comment]
Yes, I have three M1's and three Intel Macs.

**Comment by joeyballentine** [comment]
I think ncnn and onnx just don't support M1. Nothing I can do about that unfortunately

**Comment by v0nreagan** [comment]
OK, no worries, if it's not a bug, it's not a bug. Many thanks for getting it fixed for us, pytorch upscalers work like a charm now.

**Comment by andyderuyter** [comment]
> OK, no worries, if it's not a bug, it's not a bug. Many thanks for getting it fixed for us, pytorch upscalers work like a charm now.

Can you link the upscalers that do work for you? I'm having issues where my app kust keeps 'running' the upscaler without anything working (except eating RAM like Cookie Monster) :/

**Comment by joeyballentine** [comment]
@andyderuyter on mac, pytorch is going to use your CPU to upscale, so upscaling large images is going to take a long time and use lots of ram (and seem like it's doing nothing). For Intel macs I would normally recommend using ncnn (which uses your GPU via vulkan), but on m1 that is not an option. I'm looking into if it's possible to compile ncnn for arm macos. If it is, then it will be possible to use that instead of pytorch. Until then, CPU upscaling is the only option.

**Comment by joeyballentine** [comment]
@v0nreagan are you in the chaiNNer discord and would you mind testing out the new NCNN .whl I compiled? I want to see if it is able to be installed on an M1 mac
