### ISSUE TITLE
it gives this error with popup window on first boot

### ISSUE THREAD

**Issue by skyport** [joeyballentine/chaiNNer#756]
Error:
```UnhandledRejection TypeError: Object has been destroyed
    at n.loadURL (node:electron/js2c/browser_init:33:1843)
    at App.mr (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:77320)
```
OS: macOS 10.17

**Comment by skyport** [comment]
it gives this error with popup window on first boot. 
  Model Name:	MacBook Air
  Model Identifier:	MacBookAir 10,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB
  System Firmware Version:	7459.101.3
  OS Loader Version:	7459.101.3

**Comment by joeyballentine** [comment]
Duplicate of #748. This issue has been reported a few times and we are currently looking into it.

Thank you for sharing your full system information. Hopefully we can figure out what's going wrong soon. As this is a duplicate ticket, I will be closing it.

**Comment by RunDevelopment** [comment]
@joeyballentine This is not a duplicate.

#748 fails because of `IpcMainImpl.handle`, so [here](https://github.com/joeyballentine/chaiNNer/blob/3d57f4ddd379b1df32f04c1f3573cf0827ef0a7e/src/main/main.ts#L37). But this issue fails at `loadURL`, so [here](https://github.com/joeyballentine/chaiNNer/blob/3d57f4ddd379b1df32f04c1f3573cf0827ef0a7e/src/main/main.ts#L532). They are different.

**Comment by joeyballentine** [comment]
Oh, good catch

**Comment by joeyballentine** [comment]
@skyport, could you please try the [latest release](https://github.com/joeyballentine/chaiNNer/releases/tag/v0.11.2) and see if it resolves your issues?

**Comment by joeyballentine** [comment]
I believe this has been resolved. If it has not, please let me know and I will reopen this issue.

**Comment by skyport** [comment]
Hi Joey, 
Sorry, unfortunately not fixed and now there is another error than the first time. When running the program for the first time, it tries to download dependencies and this error occurs.
Bests,
